schema = 3

[mod]
  [mod.'github.com/go-task/slim-sprig/v3']
    version = 'v3.0.0'
    hash = 'sha256-vCCw4MXVBm33VNLXcOBccVDD1CSnzDvDdWB6w5FN1cA='

  [mod.'github.com/google/pprof']
    version = 'v0.0.0-20250418163039-24c5476c6587'
    hash = 'sha256-1UV7g/uLW1DJRFJOL82vcOLUscwSSH/QokqLaxDG/yM='

  [mod.'github.com/onsi/ginkgo/v2']
    version = 'v2.23.4'
    hash = 'sha256-AVq5cBqBhja/BMSMHqeLkXjmYV8+ddTRthiGWt28c38='

  [mod.'github.com/stretchr/testify']
    version = 'v1.10.0'
    hash = 'sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI='

  [mod.'go.uber.org/automaxprocs']
    version = 'v1.6.0'
    hash = 'sha256-a/Agm+kM9x+VRo0CYyTL3ipUYv9Glrc4NeGSZJdpobA='

  [mod.'golang.org/x/text']
    version = 'v0.24.0'
    hash = 'sha256-qFbmteGOvJfvbLXiOSI8Fsz5Ixt2ZhSYx0/sIqApC7Y='

  [mod.'golang.org/x/tools']
    version = 'v0.32.0'
    hash = 'sha256-nCcgtl0trmuGKWvMkJ2Rn4Q8CnNATdVrBfA1sgLGPUk='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.6'
    hash = 'sha256-lT5qnefI5FDJnowz9PEkAGylH3+fE+A3DJDkAyy9RMc='
