schema = 3

[mod]
  [mod.'connectrpc.com/connect']
    version = 'v1.21.0'
    hash = 'sha256-lER5q31oGHmc3fvgY6B1EpKxPL65vj9Wbcav3MA9JBQ='

  [mod.'github.com/go-logr/logr']
    version = 'v1.4.2'
    hash = 'sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI='

  [mod.'github.com/go-task/slim-sprig/v3']
    version = 'v3.0.0'
    hash = 'sha256-vCCw4MXVBm33VNLXcOBccVDD1CSnzDvDdWB6w5FN1cA='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/pprof']
    version = 'v0.0.0-20250418163039-24c5476c6587'
    hash = 'sha256-1UV7g/uLW1DJRFJOL82vcOLUscwSSH/QokqLaxDG/yM='

  [mod.'github.com/onsi/ginkgo/v2']
    version = 'v2.23.4'
    hash = 'sha256-AVq5cBqBhja/BMSMHqeLkXjmYV8+ddTRthiGWt28c38='

  [mod.'github.com/onsi/gomega']
    version = 'v1.36.3'
    hash = 'sha256-gKaNfZusW1jdISyxfESwwWT/4RiFHF+1Zz7XmFgkTPk='

  [mod.'github.com/stretchr/testify']
    version = 'v1.10.0'
    hash = 'sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI='

  [mod.'go.uber.org/automaxprocs']
    version = 'v1.6.0'
    hash = 'sha256-a/Agm+kM9x+VRo0CYyTL3ipUYv9Glrc4NeGSZJdpobA='

  [mod.'golang.org/x/net']
    version = 'v0.59.0'
    hash = 'sha256-EGnbU9mIAvXqx4vEIWJDt+lZgs/YsUngAFJwmFSc5Tc='

  [mod.'golang.org/x/sys']
    version = 'v0.48.0'
    hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='

  [mod.'golang.org/x/text']
    version = 'v0.42.0'
    hash = 'sha256-bviKbNmkN4Yf2dpgwmP6yNcZEakCcv1R+YyAxCdJGkY='

  [mod.'golang.org/x/tools']
    version = 'v0.49.0'
    hash = 'sha256-3oaXp2PlfuIn6/UTarnYD279YqJKTyaCWT/KD7ABjD4='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.12'
    hash = 'sha256-MKd0AdkWEe2A79mGPzOY5I76nMqTsGJKQNPJOKyOwkQ='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
