name: Buf CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    env:
      # renovate: dataSource=github-tags depName=bufbuild/buf extractVersion=^v(?<version>.*)$
      BUF_VERSION: 1.53.0
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          version: ${{ env.BUF_VERSION }}
